version: '3.3'
services:
  atm-core:
    container_name: atm-core
    image: njilrem/atm-core
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: /server
    networks:
      - app-network
    depends_on:
      - db
  db:
    container_name: atm-db
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - bank:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  bank: